mediaserver_address = "localhost"
//mediaserver_address = "192.168.178.25"
//mediaserver_address = "localhost:3000"
mediaserver_path = "media/"
local_media_path = "/Library/WebServer/Documents/media"
